# permissions for end users to view servicebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: servicebinding-viewer-role
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - servicebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - servicebindings/status
  verbs:
  - get
