apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: service-binding-edit
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - servicebindings
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: service-binding-view
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - servicebindings
    verbs:
      - get
      - list
      - watch
